version: "3"
services:
  auth:
    build: ./Auth/.
    ports:
      - "3000:3000"
    volumes:
      - ./Auth:/home/node/emailer
      - /home/node/emailer/node_modules
    links:
      - db
    environment:
      PSQL_CONNECTION_STRING=postgresql: postgresql://postgres:emailer@db:5432/emailer

  db:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy -instances=emailer-301417:us-central1:emailcore-psql=tcp:0.0.0.0:5432
    volumes:
      - /home/divyu/repos/emailer/localDb/.config/:/config
    ports:
      - "5432:5432"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/cred.json
