
### **************************************************************************************************************

### New registration call. 

POST http://0.0.0.0:3000/user/register
Content-Type: application/json
 
{
    "username": "necromancer_",
    "password": "Dibyasom@2001",
    "email": "dibya.secret@gmail.com",
    "fullname": "Dibyasom Puhan",
    "phoneno": "9668766409",
    "usertype": true
}

### New registration call.

POST http://0.0.0.0:8080/user/register
Content-Type: application/json

{
    "username": "nakulBhaiya",
    "password": "mojito",
    "email": "xyz@gmail.com",
    "fullname": "Nakul Bhaiya",
    "phoneno": "1234567890",
    "usertype": true
}

### **************************************************************************************************************

### User login call. [Authenticate and authorization (returns jwt)]
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "necromancer_",
    "password": "Dibyasom@2001"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "kylo_ren",
    "password": "emailer1234"
}

### **************************************************************************************************************
 
### JWT signed calls only.
GET http://localhost:3000/recent-emails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJUeXBlIjp0cnVlLCJpYXQiOjE2MTIyODgxMjB9.oBJxpRU4OAnY6zG4MYP6ns56Fh8ZQlJg0HBPNjzkMvw
### 

GET http://localhost:3000/recent-emails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJUeXBlIjp0cnVlLCJpYXQiOjE2MTE2ODQxMTh9.52UrTXA1GMf2aLesOKUJN3f864j-y6Bp5w_ph4U4vwI

###

GET http://localhost:3000/greet