version: "3.8"
services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: emailer1234
      POSTGRES_USER: postgres
      POSTGRESS_DB: emailer
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    image: emailer-image:1
    depends_on:
      - db
    ports:
      - "3000:3000"
